// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Deleted.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Deleted TABLE
class TableDeleted extends SqfEntityTableBase {
  TableDeleted() {
    // declare properties of EntityTable
    tableName = 'deleted';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_unique;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('img_id', DbType.text, isNotNull: false),
      SqfEntityFieldBase('cloud', DbType.bool, isNotNull: false),
      SqfEntityFieldBase('date', DbType.datetime,
          isNotNull: false, minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableDeleted();
  }
}
// END TABLES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TableDeleted.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Deleted
class Deleted {
  Deleted({this.id, this.img_id, this.cloud, this.date}) {
    _setDefaultValues();
  }
  Deleted.withFields(this.id, this.img_id, this.cloud, this.date) {
    _setDefaultValues();
  }
  Deleted.withId(this.id, this.img_id, this.cloud, this.date) {
    _setDefaultValues();
  }
  Deleted.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['img_id'] != null) {
      img_id = o['img_id'] as String;
    }
    if (o['cloud'] != null) {
      cloud = o['cloud'] == 1 || o['cloud'] == true;
    }
    if (o['date'] != null) {
      date = int.tryParse(o['date'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['date'].toString()))
          : DateTime.tryParse(o['date'].toString());
    }

    isSaved = true;
  }
  // FIELDS (Deleted)
  int id;
  String img_id;
  bool cloud;
  DateTime date;
  bool isSaved;
  BoolResult saveResult;
  // end FIELDS (Deleted)

  static const bool _softDeleteActivated = false;
  DeletedManager __mnDeleted;

  DeletedManager get _mnDeleted {
    return __mnDeleted = __mnDeleted ?? DeletedManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (img_id != null) {
      map['img_id'] = img_id;
    }

    if (cloud != null) {
      map['cloud'] = forQuery ? (cloud ? 1 : 0) : cloud;
    }

    if (date != null) {
      map['date'] = forJson
          ? date.toString()
          : forQuery ? date.millisecondsSinceEpoch : date;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (img_id != null) {
      map['img_id'] = img_id;
    }

    if (cloud != null) {
      map['cloud'] = forQuery ? (cloud ? 1 : 0) : cloud;
    }

    if (date != null) {
      map['date'] = forJson
          ? date.toString()
          : forQuery ? date.millisecondsSinceEpoch : date;
    }

    return map;
  }

  /// This method returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      id,
      img_id,
      cloud,
      date != null ? date.millisecondsSinceEpoch : null
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      img_id,
      cloud,
      date != null ? date.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Deleted>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Deleted.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Deleted>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Deleted>[];
    try {
      objList = list
          .map((deleted) => Deleted.fromMap(deleted as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Deleted.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Deleted>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Deleted> objList = <Deleted>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Deleted.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Deleted by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Deleted if exist, otherwise returns null
  Future<Deleted> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Deleted obj;
    final data = await _mnDeleted.getById([id]);
    if (data.length != 0) {
      obj = Deleted.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Deleted) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0 || !isSaved) {
      await _mnDeleted.insert(this);
      if (saveResult != null && saveResult.success) {
        isSaved = true;
      }
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnDeleted.update(this);
    }

    return id;
  }

  /// saveAll method saves the sent List<Deleted> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  Future<List<dynamic>> saveAll(List<Deleted> deleteds) async {
    // final results = _mnDeleted.saveAll('INSERT OR REPLACE INTO deleted (id,img_id, cloud, date)  VALUES (?,?,?,?)',deleteds);
    // return results; removed in sqfentity_gen 1.3.0+6
    MyDbModel().batchStart();
    for (final obj in deleteds) {
      await obj.save();
    }
    return MyDbModel().batchCommit();
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnDeleted.rawInsert(
              'INSERT OR REPLACE INTO deleted (id,img_id, cloud, date)  VALUES (?,?,?,?)',
              [
                id,
                img_id,
                cloud,
                date != null ? date.millisecondsSinceEpoch : null
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Deleted id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Deleted id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Deleted Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Deleted>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Deleted> deleteds) async {
    final results = await _mnDeleted.rawInsertAll(
        'INSERT OR REPLACE INTO deleted (id,img_id, cloud, date)  VALUES (?,?,?,?)',
        deleteds);
    return results;
  }

  /// Deletes Deleted

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Deleted invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnDeleted
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnDeleted.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  DeletedFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return DeletedFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  DeletedFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return DeletedFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isSaved = false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion deleted

// region DeletedField
class DeletedField extends SearchCriteria {
  DeletedField(this.deletedFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  DeletedFilterBuilder deletedFB;

  DeletedField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  DeletedFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param, SqlSyntax.EQuals,
            deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param, SqlSyntax.NotEQuals,
            deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.EQualsOrNull, deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder isNull() {
    deletedFB._addedBlocks = setCriteria(
        0,
        deletedFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      deletedFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          deletedFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          deletedFB._addedBlocks);
      _waitingNot = '';
      deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
          deletedFB._addedBlocks.retVal;
    }
    return deletedFB;
  }

  DeletedFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      deletedFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          deletedFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          deletedFB._addedBlocks);
      _waitingNot = '';
      deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
          deletedFB._addedBlocks.retVal;
      deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
          deletedFB._addedBlocks.retVal;
    }
    return deletedFB;
  }

  DeletedFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      deletedFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          deletedFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          deletedFB._addedBlocks);
      _waitingNot = '';
      deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
          deletedFB._addedBlocks.retVal;
    }
    return deletedFB;
  }

  DeletedFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      deletedFB._addedBlocks = setCriteria(
          pFirst,
          deletedFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          deletedFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        deletedFB._addedBlocks = setCriteria(pFirst, deletedFB.parameters,
            param, SqlSyntax.LessThan, deletedFB._addedBlocks);
      } else {
        deletedFB._addedBlocks = setCriteria(pFirst, deletedFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, deletedFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        deletedFB._addedBlocks = setCriteria(pLast, deletedFB.parameters, param,
            SqlSyntax.GreaterThan, deletedFB._addedBlocks);
      } else {
        deletedFB._addedBlocks = setCriteria(pLast, deletedFB.parameters, param,
            SqlSyntax.LessThanOrEquals, deletedFB._addedBlocks);
      }
    }
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.GreaterThan, deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.LessThanOrEquals, deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param, SqlSyntax.LessThan,
            deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param, SqlSyntax.LessThan,
            deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    deletedFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.LessThanOrEquals, deletedFB._addedBlocks)
        : setCriteria(pValue, deletedFB.parameters, param,
            SqlSyntax.GreaterThan, deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }

  DeletedFilterBuilder inValues(dynamic pValue) {
    deletedFB._addedBlocks = setCriteria(
        pValue,
        deletedFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        deletedFB._addedBlocks);
    _waitingNot = '';
    deletedFB._addedBlocks.needEndBlock[deletedFB._blockIndex] =
        deletedFB._addedBlocks.retVal;
    return deletedFB;
  }
}
// endregion DeletedField

// region DeletedFilterBuilder
class DeletedFilterBuilder extends SearchCriteria {
  DeletedFilterBuilder(Deleted obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Deleted _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  DeletedFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  DeletedFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  DeletedFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  DeletedFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param =
          DbParameter(columnName: parameterValue == null ? null : '');
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  DeletedFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  DeletedFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  DeletedFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  DeletedFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  DeletedFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  DeletedFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s != '') {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  DeletedField setField(DeletedField field, String colName, DbType dbtype) {
    return DeletedField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  DeletedField _id;
  DeletedField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  DeletedField _img_id;
  DeletedField get img_id {
    return _img_id = setField(_img_id, 'img_id', DbType.text);
  }

  DeletedField _cloud;
  DeletedField get cloud {
    return _cloud = setField(_cloud, 'cloud', DbType.bool);
  }

  DeletedField _date;
  DeletedField get date {
    return _date = setField(_date, 'date', DbType.datetime);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Deleted._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Deleted> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Deleted._softDeleteActivated && !hardDelete) {
      r = await _obj._mnDeleted.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnDeleted.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from deleted ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnDeleted.updateBatch(qparams, values);
  }

  /// This method always returns Deleted Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Deleted>
  Future<Deleted> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnDeleted.toList(qparams);
    final data = await objFuture;
    Deleted obj;
    if (data.isNotEmpty) {
      obj = Deleted.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) deletedCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final deletedsFuture = await _obj._mnDeleted.toList(qparams);
    final int count = deletedsFuture[0]['CNT'] as int;
    if (deletedCount != null) {
      deletedCount(count);
    }
    return count;
  }

  /// This method returns List<Deleted>.
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Deleted>
  Future<List<Deleted>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Deleted> deletedsData = await Deleted.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return deletedsData;
  }

  /// This method returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnDeleted.toList(qparams);
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnDeleted.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnDeleted.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Deleted.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnDeleted.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion DeletedFilterBuilder

// region DeletedFields
class DeletedFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fImg_id;
  static TableField get img_id {
    return _fImg_id =
        _fImg_id ?? SqlSyntax.setField(_fImg_id, 'img_id', DbType.text);
  }

  static TableField _fCloud;
  static TableField get cloud {
    return _fCloud =
        _fCloud ?? SqlSyntax.setField(_fCloud, 'cloud', DbType.bool);
  }

  static TableField _fDate;
  static TableField get date {
    return _fDate =
        _fDate ?? SqlSyntax.setField(_fDate, 'date', DbType.datetime);
  }
}
// endregion DeletedFields

//region DeletedManager
class DeletedManager extends SqfEntityProvider {
  DeletedManager()
      : super(MyDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'deleted';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion DeletedManager
class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
